### ISSUE TITLE
Tags should be limited to python identifiers

### ISSUE THREAD

**Issue by colinjbrown** [dataflownb/dfnotebook-extension#20]
_From @dakoop on Mar 1, 2024_
Tags with spaces or escape chars can cause problems for the tokenizer so it is best to limit them to valid python identifiers so they mesh with the $ syntax extension. We need to check on the frontend entry for this.

_From @colinjbrown on Mar 1, 2024_

Note: regarding tags we should look at the regex that reads in the stale notebook to figure out the links in the code, we rely on 
```let regex = /\w+\$[a-f0-9]{8}/g``` at https://github.com/dataflownb/dfnotebook-extension/blob/dfnb-tests-wip/packages/dfnotebook-extension/src/index.ts#L402 to parse in the links between cells (this has also been impacted by the changes at https://github.com/dataflownb/dfnotebook-extension/commit/d03e91b6e57aa57e6f2ea87ecf58d9bbdf9785e8) 

This issue should be closed when we move to saving the dfgraph into the metadata

**Comment by dakoop** [comment]
Can we just use [str.isidentifier](https://docs.python.org/3/library/stdtypes.html#str.isidentifier) here?

**Comment by colinjbrown** [comment]
That sounds reasonable to me, one issue that I see is that this is on the typescript side so we'd need to pass the message to the Python side to validate that

**Comment by colinjbrown** [comment]
Here's an example error output

![image](https://github.com/dataflownb/dfnotebook-extension/assets/29678835/7d682758-eaa3-4d3a-8603-bc717d81d7ba)

**Comment by BradPohl** [comment]
Tags should not be able to be duplicated down stream. Currently, if a tag is duplicated (even with different variable names), the most recent ran tag will be used and an error is thrown. We need a way to grab cell names and iterate through on the frontend side to check for possible reused names.
